### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by eumiro**
First let's see whether it runs …

### CODE REVIEW

**Comment by eumiro** [comment]
Looks like it works. The results are visible at https://github.com/eumiro/eve/actions until you merge this.

**Comment by nicolaiarocci** [comment]
rebased and merged, thank you.

**Comment by nicolaiarocci** [comment]
@eumiro two things:

- Docs don't have the GH Action CI badge yet;
- Once the above is done, I think we are ready to drop travis

**Comment by eumiro** [comment]
What do you mean by the docs missing the GHA CI badge? There's a badge in the README.rst file.

**Comment by nicolaiarocci** [comment]
if you go to python-eve.org you get a different file rendered on the homepage (https://github.com/pyeve/eve/blob/master/docs/index.rst)

**Pull request closed without merging**
