### PR TITLE
Fix a bug that PATCH will override the default fields

### PR DESCRIPTION
**Pull request by zhangtemplar**
#1234

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
rebased, reformatted, and merged. Thanks!

**Comment by nicolaiarocci** [comment]
It is actually failing, see https://travis-ci.org/pyeve/eve/jobs/513393185

Could you please look into it?

**Comment by zhangtemplar** [comment]
@nicolaiarocci Yes, I am working on it.

**Comment by nicolaiarocci** [comment]
@zhangtemplar alright. meanwhile, I reverted the merge so we don't have failing CI on every other PR. Please open a new PR when ready.

**Pull request closed without merging**
