### PR TITLE
Add linux wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add Linux wheel build support.

Related to https://github.com/pyeve/eve/issues/1480 @nicolaiarocci  Could you please review this PR?

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hi, thanks for this. Won't this upload dev wheels to PyPI? I'd rather only upload stable versions.

**Comment by odidev** [comment]
I have done the changes. Now the wheel will build but upload only when the tags are released.

**Comment by nicolaiarocci** [comment]
I have uploaded a Eve 2 wheel to PYPI. Can you please confirm if it works for you? This one was built at the Eve 2 release (June 8); just not uploaded to the package service.

**Comment by odidev** [comment]
@nicolaiarocci Yes, the wheels are working on both Linux x86_64 and aarch64.

**Comment by nicolaiarocci** [comment]
Thanks for this contribution. For the time being I'll be happy with manually uploading wheels on release. I'll keep this code around in case I feel like automating the process.

**Pull request closed without merging**
