### PR TITLE
Prune the stages from aggregation pipeline whose condition is not set…

### PR DESCRIPTION
**Pull request by zhangtemplar**
… or empty.

### CODE REVIEW

**Comment by zhangtemplar** [comment]
@nicolaiarocci how should I mute the warnings for:
```
eve/tests/renders.py:201:22: W605 invalid escape sequence '\d'
eve/tests/renders.py:201:27: W605 invalid escape sequence '\.'
eve/tests/renders.py:201:35: W605 invalid escape sequence '\.'
```

**Comment by zhangtemplar** [comment]
OK, it turns out to be much more complex than I thought.

I cannot simply prune out all values starting with $, as MongoDB some times strings starts with $ also refer to a field in the document.

The alternative is that, user should always provide parameter for the variables in the aggregation pipeline; however, for the variables which are intended to omit/ignore, set `{}` to those variables.

**Comment by nicolaiarocci** [comment]
rebased and merged. Thanks.

**Comment by zhangtemplar** [comment]
Cool

**Pull request closed without merging**
