### PR TITLE
[WIP] Replace Flask-PyMongo (fixes #855)

### LINKED ISSUE #855: How to connect using multiple nodes
Hi, thank you for this awesome project!

I am having trouble trying to connect to a Mongo 3.2.1 database which uses this string, provided by [Compose.io](https://compose.io/):

`mongodb://<user>:<password>@<host1>:<port1>,<host2>:<port2>/<db-name>?ssl=true
`

I tried using MONGO_URI in the configuration dictionary but it tries to connect to a local server:

```
/vagrant/env/local/lib/python2.7/site-packages/pymongo/topology.pyc in select_servers(self, selector, server_selection_timeout, address)
    116                 if server_timeout == 0 or now > end_time:
    117                     raise ServerSelectionTimeoutError(
--> 118                         self._error_message(selector))
    119 
    120                 self._ensure_opened()

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

Not sure how can I set my connection string, currently I am using just one node using these variables:

```
MONGO_HOST
MONGO_PORT
MONGO_DBNAME
MONGO_USERNAME
MONGO_PASSWORD
```

But I need to be able to use both to handle failover between nodes.

Any idea?

### PR DESCRIPTION
**Pull request by tyomo4ka**
This is _work in progress_ PR.

Flask-PyMongo is abandoned and is not compatible with latests PyMongo version.
This PR removes this dependency in Eve framewrok.

TODO:

- [x] priority for auth parameters if specified both in MONGO_URL and MONGO_AUTH params. 
- [x] pymongo kwargs validation
- [x] tests for flask_pymongo module
- [x] new tests for authentication
- [x] fix CI tests
- [x] Decide what to do with MONGO_OPTIONS
- [x] documentation

Hey @nicolaiarocci Could you please review this PR and let me know if I moving into right direction. 

Feel free to add stuff in TODO if any.

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
This is stellar work, thank you.

**Comment by tyomo4ka** [comment]
@nicolaiarocci 

I need your advice.

We have three different ways to pass PyMongo connection options to PyMongo client.

1. In `MONGO_URL`. It's simple. There is only one config option which you need to care about.
2. Using per-option Eve settings. I.e. we translate Eve settings `MONGO_CONNECT` into `connect` keyword argument for example.
3. Pass them using `MONGO_OPTIONS`.

I initially wanted to implement 1 and 2. Supporting of 1, 2 and 3 seems like an overhead to me. And it will be even more mess with priorities if the same options specified in different places.

1 and 2 has been implemented, but I think it's better to drop option 2 and implement 3 instead. It will be easier to support it in long term perspective. If PyMongo releases changes in options everything we need to do reference the proper version in PyMongo documentation. 

What do you think?

**Comment by nicolaiarocci** [comment]
I agree, let's get rid of obsolete stuff.  This will also need of course a documentation upgrade (and breaking changes reported in the changelog).

**Comment by tyomo4ka** [comment]
@nicolaiarocci It's ready for review now.

**Comment by nicolaiarocci** [comment]
Excellent.

**Comment by nicolaiarocci** [comment]
Merged after rebase to branch [v0.8](https://github.com/pyeve/eve/tree/v0.8)

Thanks!

**Pull request closed without merging**
