### PR TITLE
fix flask 2.2 tests

### PR DESCRIPTION
**Pull request by smeng9**
Closes https://github.com/pyeve/eve/issues/1485

### CODE REVIEW

**Comment by smeng9** [comment]
Hi @nicolaiarocci 

There seems to have some issue on the CI pipeline itself

**Comment by nicolaiarocci** [comment]
hi @smeng9 could you please rebase on top of master and try again? See #1499.

**Comment by nicolaiarocci** [comment]
nervermind, I rebased and merged myself. Thanks!

**Comment by smeng9** [comment]
Do we have an estimated release schedule for the 2.0.5 that supports flask 2.2?

**Comment by nicolaiarocci** [comment]
v2.1 has just been released, see https://pypi.org/project/Eve/2.1.0/

**Pull request closed without merging**
