### PR TITLE
Bug on bulk delete + Embedded callback

### PR DESCRIPTION
**Pull request by Amedeo91**
Wih those changes, it will be possible to do the bulk delete when the soft delete is enable even when the id_field is not the _id

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hello, thanks for this. Would you please squash all commits into one?

**Comment by Amedeo91** [comment]
Ciao Nicola, commit uniti! :)

**Comment by nicolaiarocci** [comment]
Ciao! 

Awesome, I will review your code in the near future (I hope).

**Comment by Amedeo91** [comment]
Hi Nicola, I add something else in my PR in order to simplify the development of the problem exposed in the issue 1010. This way, I can modify a bit the Eve logic in order to support doing queries using some other filter (than only the _id) when embedding.

**Comment by Amedeo91** [comment]
Ciao Nicola,

I add the test. 

Regards,
Amedeo

**Comment by Amedeo91** [comment]
Hi Nicola, 

Waiting for you code review! :)

Regards,
Amedeo

**Comment by nicolaiarocci** [comment]
I am sorry but there is too much stuff going on in here, I cannot accept different features with the same PR. Could you split this into separate ones. Also make sure you document what you are trying to achieve, and what is your use case (link the relevant issue if needed, by like #1010)

**Comment by Amedeo91** [comment]
Hi Nicola, 
in my PR there are two things:
               1) Adding a callback for embedded document feature
               2) Fixing a bug on the Soft Bulk Delete (plus, adding a callback suitable for something)

Please, confirm that you actually want two separate PR or if you are fine with one.

Regards,
Amedeo

**Comment by nicolaiarocci** [comment]
Please open a ticket for the 'delete bug'. When acknowledged, submit a PR to fix it. One concern, one ticket, one pull request if needed. Thanks.

**Comment by Amedeo91** [comment]
Ok, I will reject this

**Pull request closed without merging**
